# Generated by Django 5.1.4 on 2025-08-07 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='input text')),
                ('output_text', models.TextField(verbose_name='output text')),
                ('context', models.CharField(blank=True, max_length=255, verbose_name='context')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI chat history',
                'verbose_name_plural': 'AI chat history',
                'db_table': 'ai_chat_history',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='image')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_videos/', verbose_name='video')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='scheduled time')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('canva_design_id', models.CharField(blank=True, max_length=255, verbose_name='canva design id')),
                ('drive_file_id', models.CharField(blank=True, max_length=255, verbose_name='drive file id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social post',
                'verbose_name_plural': 'social posts',
                'db_table': 'social_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255, verbose_name='stripe subscription id')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('last_payment', models.DateTimeField(verbose_name='last payment')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_word', models.CharField(max_length=255, verbose_name='trigger word')),
                ('message_template', models.TextField(verbose_name='message template')),
                ('redirect_link', models.URLField(blank=True, verbose_name='redirect link')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trigger rule',
                'verbose_name_plural': 'trigger rules',
                'db_table': 'trigger_rules',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('display_name', models.CharField(max_length=255, verbose_name='display name')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile image')),
                ('embedded_video', models.URLField(blank=True, verbose_name='embedded video')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('url', models.URLField(verbose_name='url')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='link_thumbnails/', verbose_name='thumbnail')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_links', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'custom link',
                'verbose_name_plural': 'custom links',
                'db_table': 'custom_links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('button_text', models.CharField(max_length=100, verbose_name='button text')),
                ('button_url', models.URLField(verbose_name='button url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta_banner', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'CTA banner',
                'verbose_name_plural': 'CTA banners',
                'db_table': 'cta_banners',
            },
        ),
        migrations.CreateModel(
            name='PostPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=50, verbose_name='platform')),
                ('posted', models.BooleanField(default=False, verbose_name='posted')),
                ('post_id', models.CharField(blank=True, max_length=255, verbose_name='post id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_platforms', to='api.socialpost')),
            ],
            options={
                'verbose_name': 'post platform',
                'verbose_name_plural': 'post platforms',
                'db_table': 'post_platforms',
                'unique_together': {('social_post', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest')], max_length=50, verbose_name='platform')),
                ('access_token', models.TextField(verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='refresh token')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('platform_user_id', models.CharField(blank=True, max_length=255, verbose_name='platform user id')),
                ('platform_username', models.CharField(blank=True, max_length=255, verbose_name='platform username')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social token',
                'verbose_name_plural': 'social tokens',
                'db_table': 'social_tokens',
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('github', 'GitHub'), ('website', 'Website')], max_length=50, verbose_name='platform')),
                ('url', models.URLField(verbose_name='url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_icons', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'social icon',
                'verbose_name_plural': 'social icons',
                'db_table': 'social_icons',
                'unique_together': {('user_profile', 'platform')},
            },
        ),
    ]
