# Generated by Django 5.1.4 on 2025-08-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aichathistory_socialpost_subscription_triggerrule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='socialtoken',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostPlatform',
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
        migrations.DeleteModel(
            name='SocialToken',
        ),
    ]
