# Generated by Django 5.1.4 on 2025-08-10 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_socialpost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest')], max_length=50, unique=True, verbose_name='platform name')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('client_id', models.CharField(max_length=255, verbose_name='client id')),
                ('client_secret', models.CharField(max_length=255, verbose_name='client secret')),
                ('auth_url', models.URLField(verbose_name='authorization url')),
                ('token_url', models.URLField(verbose_name='token url')),
                ('scope', models.TextField(help_text='Comma-separated list of required scopes', verbose_name='scope')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'social media platform',
                'verbose_name_plural': 'social media platforms',
                'db_table': 'social_media_platforms',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='token type')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('scope', models.TextField(blank=True, verbose_name='granted scope')),
                ('platform_user_id', models.CharField(blank=True, max_length=255, verbose_name='platform user id')),
                ('platform_username', models.CharField(blank=True, max_length=255, verbose_name='platform username')),
                ('platform_display_name', models.CharField(blank=True, max_length=255, verbose_name='platform display name')),
                ('platform_profile_url', models.URLField(blank=True, verbose_name='platform profile url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.socialmediaplatform')),
            ],
            options={
                'verbose_name': 'social media connection',
                'verbose_name_plural': 'social media connections',
                'db_table': 'social_media_connections',
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='post text')),
                ('media_urls', models.JSONField(blank=True, default=list, verbose_name='media urls')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('platform_post_id', models.CharField(blank=True, max_length=255, verbose_name='platform post id')),
                ('platform_post_url', models.URLField(blank=True, verbose_name='platform post url')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.socialmediaconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social media post',
                'verbose_name_plural': 'social media posts',
                'db_table': 'social_media_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('text_template', models.TextField(verbose_name='text template')),
                ('media_urls', models.JSONField(blank=True, default=list, verbose_name='media urls')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('platforms', models.ManyToManyField(related_name='templates', to='api.socialmediaplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social media post template',
                'verbose_name_plural': 'social media post templates',
                'db_table': 'social_media_post_templates',
            },
        ),
    ]
