# Generated by Django 5.1.4 on 2025-08-13 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_socialmediaplatform_socialmediaconnection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, help_text='Facebook profile URL', verbose_name='Facebook')),
                ('pinterest', models.URLField(blank=True, help_text='Pinterest profile URL', verbose_name='Pinterest')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL', verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL', verbose_name='TikTok')),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL', verbose_name='YouTube')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL', verbose_name='Twitter/X')),
                ('website', models.URLField(blank=True, help_text='Personal website URL', verbose_name='Personal Website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user social links',
                'verbose_name_plural': 'user social links',
                'db_table': 'user_social_links',
            },
        ),
    ]
