# Generated by Django 5.1.4 on 2025-08-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the plan', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this plan includes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID', max_length=255)),
                ('trial_period_days', models.PositiveIntegerField(default=14, help_text='Number of days for free trial')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for new subscriptions')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this plan in pricing display')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_payment',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trialing',
            field=models.BooleanField(default=False, help_text='Whether subscription is currently in trial period'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for backwards compatibility', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, help_text='When the trial period started', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The subscribed plan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.plan'),
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text="Technical key for feature (e.g., 'max_audits', 'has_priority_support')", max_length=100)),
                ('feature_name', models.CharField(help_text='Human-readable feature name', max_length=200)),
                ('feature_value', models.CharField(help_text="Feature value (e.g., '10', 'unlimited', 'true')", max_length=100)),
                ('is_highlight', models.BooleanField(default=False, help_text='Show this feature prominently in pricing')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.plan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'db_table': 'plan_features',
                'ordering': ['sort_order', 'feature_name'],
                'unique_together': {('plan', 'feature_key')},
            },
        ),
    ]
