# Generated by Django 5.1.4 on 2025-08-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plan_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaconnection',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Page ID'),
        ),
        migrations.AddField(
            model_name='socialmediaconnection',
            name='facebook_page_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Page Name'),
        ),
        migrations.AddField(
            model_name='socialmediaconnection',
            name='instagram_business_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instagram Business ID'),
        ),
        migrations.AddField(
            model_name='socialmediaconnection',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instagram Username'),
        ),
    ]
