# Generated by Django 5.1.4 on 2025-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_socialmediaconnection_facebook_page_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediaconnection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='socialmediaconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('facebook_page_id__isnull', False)), fields=('user', 'platform', 'facebook_page_id'), name='unique_facebook_connection'),
        ),
        migrations.AddConstraint(
            model_name='socialmediaconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_business_id__isnull', False)), fields=('user', 'platform', 'instagram_business_id'), name='unique_instagram_connection'),
        ),
    ]
