# Generated by Django 5.1.4 on 2025-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fix_social_media_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialmediaconnection',
            name='unique_facebook_connection',
        ),
        migrations.RemoveConstraint(
            model_name='socialmediaconnection',
            name='unique_instagram_connection',
        ),
        migrations.AddConstraint(
            model_name='socialmediaconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('facebook_page_id__isnull', False), models.Q(('facebook_page_id', ''), _negated=True)), fields=('user', 'platform', 'facebook_page_id'), name='unique_facebook_connection'),
        ),
        migrations.AddConstraint(
            model_name='socialmediaconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_business_id__isnull', False), models.Q(('instagram_business_id', ''), _negated=True)), fields=('user', 'platform', 'instagram_business_id'), name='unique_instagram_connection'),
        ),
    ]
