# Generated by Django 5.1.4 on 2025-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fix_empty_string_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaconnection',
            name='platform_profile_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='platform profile url'),
        ),
    ]
