# Generated by Django 5.1.4 on 2025-08-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_increase_profile_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaconnection',
            name='pinterest_user_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pinterest User ID'),
        ),
        migrations.AddConstraint(
            model_name='socialmediaconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('pinterest_user_id__isnull', False), models.Q(('pinterest_user_id', ''), _negated=True)), fields=('user', 'platform', 'pinterest_user_id'), name='unique_pinterest_connection'),
        ),
    ]
