# Generated by Django 5.1.4 on 2025-08-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_folder_media_folder_unique_folder_name_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='referrer')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='clicked at')),
                ('custom_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='api.customlink')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'link click',
                'verbose_name_plural': 'link clicks',
                'db_table': 'link_clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['user_profile', '-clicked_at'], name='link_clicks_user_pr_374190_idx'), models.Index(fields=['custom_link', '-clicked_at'], name='link_clicks_custom__d5a66f_idx'), models.Index(fields=['clicked_at'], name='link_clicks_clicked_8ce23d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='referrer')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'profile view',
                'verbose_name_plural': 'profile views',
                'db_table': 'profile_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user_profile', '-viewed_at'], name='profile_vie_user_pr_653680_idx'), models.Index(fields=['viewed_at'], name='profile_vie_viewed__2888b9_idx')],
            },
        ),
    ]
