# Generated by Django 5.1.4 on 2025-08-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_linkclick_profileview'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['ip_address', 'clicked_at'], name='link_clicks_ip_addr_6da83d_idx'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='profile_vie_ip_addr_c39b46_idx'),
        ),
    ]
