# Generated by Django 5.1.4 on 2025-08-24 05:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_linkclick_link_clicks_ip_addr_6da83d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='link_thumbnail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
