# Generated by Django 5.1.4 on 2025-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customlink_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctabanner',
            name='style',
            field=models.CharField(default='gradient-purple', max_length=50, verbose_name='style'),
        ),
    ]
