# Generated by Django 5.1.4 on 2025-08-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_style_to_cta_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctabanner',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='click count'),
        ),
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='referrer')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='api.ctabanner')),
            ],
            options={
                'verbose_name': 'banner click',
                'verbose_name_plural': 'banner clicks',
                'db_table': 'banner_clicks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['banner', '-timestamp'], name='banner_clic_banner__00d045_idx'), models.Index(fields=['timestamp'], name='banner_clic_timesta_79ce1e_idx'), models.Index(fields=['ip_address', 'timestamp'], name='banner_clic_ip_addr_fe963d_idx')],
            },
        ),
    ]
