# Generated by Django 5.1.4 on 2025-08-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ctabanner_click_count_bannerclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='click count'),
        ),
    ]
