# Generated by Django 5.1.4 on 2025-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_click_count_to_custom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='view count'),
        ),
    ]
