# Generated by Django 5.1.4 on 2025-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_view_count_to_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='media_urls',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='media_files',
            field=models.ManyToManyField(blank=True, help_text='Media files (images/videos) for this post', related_name='social_posts', to='api.media'),
        ),
    ]
