# Generated by Django 5.1.4 on 2025-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_update_post_media_to_cloudinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaconnection',
            name='platform_profile_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='platform profile url'),
        ),
    ]
