# Generated by Django 5.1.4 on 2025-08-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fix_profile_url_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255, unique=True, verbose_name='Facebook comment ID')),
                ('post_id', models.CharField(max_length=255, verbose_name='Facebook post ID')),
                ('page_id', models.CharField(max_length=255, verbose_name='Facebook page ID')),
                ('from_user_name', models.CharField(max_length=255, verbose_name='User name')),
                ('message', models.TextField(verbose_name='Comment message')),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('ignored', 'Ignored')], default='new', max_length=20, verbose_name='Status')),
                ('created_time', models.DateTimeField(verbose_name='Facebook created time')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.socialmediaconnection')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CommentAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='Rule name')),
                ('keywords', models.JSONField(default=list, verbose_name='Keywords')),
                ('reply_template', models.TextField(verbose_name='Reply template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('times_triggered', models.IntegerField(default=0, verbose_name='Times triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='api.socialmediaconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_automation_rules',
                'ordering': ['connection', '-priority'],
                'unique_together': {('user', 'connection', 'rule_name')},
            },
        ),
        migrations.CreateModel(
            name='CommentAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Automation enabled')),
                ('default_reply', models.TextField(blank=True, verbose_name='Default reply')),
                ('reply_delay_seconds', models.IntegerField(default=5, verbose_name='Reply delay (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='api.socialmediaconnection', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_automation_settings',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(verbose_name='Reply text')),
                ('facebook_reply_id', models.CharField(blank=True, max_length=255, verbose_name='Facebook reply ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.commentautomationrule')),
            ],
            options={
                'db_table': 'comment_replies',
                'ordering': ['-sent_at'],
            },
        ),
    ]
