# Generated by Django 5.1.4 on 2025-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_comment_automation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='from_user_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook user ID'),
        ),
    ]
