# Generated by Django 5.1.4 on 2025-08-28 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_from_user_id_to_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentautomationrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentautomationrule',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='commentautomationrule',
            name='user',
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='Rule name')),
                ('message_type', models.CharField(choices=[('comment', 'Comment'), ('dm', 'Direct Message'), ('both', 'Both')], default='comment', max_length=10, verbose_name='Message type')),
                ('keywords', models.JSONField(default=list, verbose_name='Keywords')),
                ('reply_template', models.TextField(verbose_name='Reply template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('times_triggered', models.IntegerField(default=0, verbose_name='Times triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='api.socialmediaconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['connection', '-priority'],
                'unique_together': {('user', 'connection', 'rule_name', 'message_type')},
            },
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to='api.automationrule'),
        ),
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Comment automation enabled')),
                ('default_reply', models.TextField(blank=True, verbose_name='Default comment reply')),
                ('reply_delay_seconds', models.IntegerField(default=5, verbose_name='Comment reply delay (seconds)')),
                ('enable_dm_automation', models.BooleanField(default=False, verbose_name='DM automation enabled')),
                ('dm_default_reply', models.TextField(blank=True, verbose_name='Default DM reply')),
                ('dm_reply_delay_seconds', models.IntegerField(default=10, verbose_name='DM reply delay (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='api.socialmediaconnection', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_settings',
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='Message ID')),
                ('conversation_id', models.CharField(max_length=255, verbose_name='Conversation ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Messenger'), ('instagram', 'Instagram DM')], max_length=20, verbose_name='Platform')),
                ('sender_id', models.CharField(max_length=255, verbose_name='Sender ID')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Sender name')),
                ('message_text', models.TextField(blank=True, verbose_name='Message text')),
                ('message_attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('ignored', 'Ignored'), ('error', 'Error')], default='new', max_length=20, verbose_name='Status')),
                ('is_echo', models.BooleanField(default=False, help_text='Message sent by the page itself', verbose_name='Is echo')),
                ('created_time', models.DateTimeField(verbose_name='Platform created time')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='api.socialmediaconnection')),
            ],
            options={
                'db_table': 'direct_messages',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(verbose_name='Reply text')),
                ('platform_reply_id', models.CharField(blank=True, max_length=255, verbose_name='Platform reply ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('error', 'Error')], default='sent', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('direct_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.directmessage')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_replies', to='api.automationrule')),
            ],
            options={
                'db_table': 'direct_message_replies',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='CommentAutomationSettings',
        ),
        migrations.DeleteModel(
            name='CommentAutomationRule',
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['platform', 'conversation_id'], name='direct_mess_platfor_59c749_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['connection', 'status'], name='direct_mess_connect_e62744_idx'),
        ),
    ]
