# Generated by Django 5.1.4 on 2025-08-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_commentautomationrule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerrule',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIChatHistory',
        ),
        migrations.DeleteModel(
            name='TriggerRule',
        ),
    ]
