# Generated by Django 5.1.4 on 2025-08-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_unused_ai_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('text_generation', 'Text Generation'), ('image_generation', 'Image Generation'), ('social_content', 'Social Media Content'), ('content_improvement', 'Content Improvement'), ('image_analysis', 'Image Analysis')], max_length=50, unique=True, verbose_name='AI capability')),
                ('system_prompt', models.TextField(blank=True, help_text='Custom system prompt for this AI capability', verbose_name='system prompt')),
                ('default_model', models.CharField(blank=True, help_text='Default AI model to use for this capability', max_length=50, verbose_name='default model')),
                ('default_temperature', models.FloatField(default=0.7, help_text='Creativity level (0.0-2.0)', verbose_name='default temperature')),
                ('default_max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum tokens to generate', verbose_name='default max tokens')),
                ('default_image_size', models.CharField(default='1024x1024', help_text='Default image size for generation', max_length=20, verbose_name='default image size')),
                ('default_image_quality', models.CharField(choices=[('standard', 'Standard'), ('hd', 'HD')], default='standard', help_text='Default image quality', max_length=20, verbose_name='default image quality')),
                ('default_image_style', models.CharField(choices=[('vivid', 'Vivid'), ('natural', 'Natural')], default='vivid', help_text='Default image style for DALL-E 3', max_length=20, verbose_name='default image style')),
                ('default_tone', models.CharField(default='professional', help_text='Default writing tone for social content', max_length=50, verbose_name='default tone')),
                ('include_hashtags_by_default', models.BooleanField(default=True, help_text='Include hashtags in social content by default', verbose_name='include hashtags by default')),
                ('default_improvement_type', models.CharField(choices=[('grammar', 'Grammar & Spelling'), ('clarity', 'Clarity & Readability'), ('engagement', 'Engagement'), ('tone', 'Professional Tone'), ('concise', 'Conciseness')], default='grammar', help_text='Default type of content improvement', max_length=50, verbose_name='default improvement type')),
                ('default_analysis_detail', models.CharField(choices=[('auto', 'Auto'), ('low', 'Low'), ('high', 'High')], default='auto', help_text='Default level of detail for image analysis', max_length=20, verbose_name='default analysis detail')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('save_generated_content', models.BooleanField(default=False, help_text='Save generated content to media directory', verbose_name='save generated content')),
                ('total_usage_count', models.PositiveBigIntegerField(default=0, verbose_name='total usage count')),
                ('total_tokens_used', models.PositiveBigIntegerField(default=0, verbose_name='total tokens used')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'AI configuration',
                'verbose_name_plural': 'AI configurations',
                'db_table': 'ai_configurations',
                'indexes': [models.Index(fields=['capability'], name='ai_configur_capabil_6cebe8_idx'), models.Index(fields=['is_active'], name='ai_configur_is_acti_341135_idx'), models.Index(fields=['last_used_at'], name='ai_configur_last_us_338818_idx')],
            },
        ),
    ]
