# Generated by Django 5.1.4 on 2025-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_ai_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_analysis_detail',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_image_quality',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_image_size',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_image_style',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_improvement_type',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_max_tokens',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_model',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_temperature',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='default_tone',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='include_hashtags_by_default',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='save_generated_content',
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='text_generation_model',
            field=models.CharField(default='gpt-4', help_text='Model to use for text generation capabilities', max_length=100, verbose_name='text generation model'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='vision_model',
            field=models.CharField(default='gpt-4-vision-preview', help_text='Model to use for image analysis capabilities', max_length=100, verbose_name='vision model'),
        ),
    ]
