# Generated by Django 5.1.4 on 2025-09-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_simplify_ai_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_overview', models.BooleanField(default=True, help_text='Dashboard section access', verbose_name='Can Access Overview')),
                ('can_access_linkinbio', models.BooleanField(default=True, help_text='Storefront, Custom Links, CTA Banners', verbose_name='Can Access Link-in-Bio')),
                ('can_access_content', models.BooleanField(default=True, help_text='Calendar, Post Creator, Content Library, Social Accounts', verbose_name='Can Access Content & Social')),
                ('can_access_automation', models.BooleanField(default=True, help_text='Comments, Automation Rules, Settings, Analytics', verbose_name='Can Access Automation')),
                ('can_access_ai_tools', models.BooleanField(default=True, help_text='AI Assistant and related tools', verbose_name='Can Access AI & Tools')),
                ('can_access_business', models.BooleanField(default=True, help_text='Subscription and billing management', verbose_name='Can Access Business')),
                ('can_access_account', models.BooleanField(default=True, help_text='Account settings and profile', verbose_name='Can Access Account')),
                ('can_edit_profile', models.BooleanField(default=True, help_text='Edit user profile and settings', verbose_name='Can Edit Profile')),
                ('can_manage_integrations', models.BooleanField(default=True, help_text='Connect/disconnect social media accounts', verbose_name='Can Manage Integrations')),
                ('can_view_analytics', models.BooleanField(default=True, help_text='View performance analytics and stats', verbose_name='Can View Analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user permissions',
                'verbose_name_plural': 'user permissions',
                'db_table': 'user_permissions',
            },
        ),
    ]
