# Generated by Django 5.1.4 on 2025-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('twitch', 'Twitch'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('reddit', 'Reddit'), ('tumblr', 'Tumblr'), ('medium', 'Medium'), ('github', 'GitHub'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('email', 'Email'), ('website', 'Website')], max_length=50, verbose_name='platform'),
        ),
    ]
