# Generated by Django 5.1.4 on 2025-09-09 09:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_socialicon_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlink',
            name='text',
        ),
        migrations.RemoveField(
            model_name='customlink',
            name='url',
        ),
        migrations.AddField(
            model_name='customlink',
            name='additional_info',
            field=models.JSONField(blank=True, help_text='Product-specific information based on product type', null=True, verbose_name='additional info'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_bottom_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='checkout bottom title'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_cta_button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='checkout CTA button text'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_description',
            field=models.TextField(blank=True, verbose_name='checkout description'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='checkout discounted price'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='checkout_image'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='checkout price'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='checkout_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='checkout title'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='style',
            field=models.CharField(choices=[('callout', 'Callout'), ('button', 'Button'), ('checkout', 'Checkout'), ('collect_info', 'Collect Info')], default='callout', max_length=20, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='customlink',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='CollectInfoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('phone', 'Phone Number'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], max_length=20, verbose_name='field type')),
                ('label', models.CharField(max_length=100, verbose_name='field label')),
                ('placeholder', models.CharField(blank=True, max_length=150, verbose_name='placeholder text')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('options', models.JSONField(blank=True, help_text='JSON array of options for multiple choice/dropdown/checkbox fields', null=True, verbose_name='field options')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('custom_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_info_fields', to='api.customlink')),
            ],
            options={
                'verbose_name': 'collect info field',
                'verbose_name_plural': 'collect info fields',
                'db_table': 'collect_info_fields',
                'ordering': ['custom_link', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CollectInfoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(help_text='JSON object with field_id: response mappings', verbose_name='form responses')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('custom_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_info_responses', to='api.customlink')),
            ],
            options={
                'verbose_name': 'collect info response',
                'verbose_name_plural': 'collect info responses',
                'db_table': 'collect_info_responses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
