# Generated by Django 5.1.4 on 2025-09-09 09:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_enhance_customlink_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='checkout_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='checkout description'),
        ),
    ]
