# Generated by Django 5.1.4 on 2025-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customlink_checkout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='type',
            field=models.CharField(default='generic', help_text="Product type (e.g., 'generic', 'digital_product', 'service', 'event', 'subscription')", max_length=50, verbose_name='type'),
        ),
    ]
