# Generated by Django 5.1.4 on 2025-09-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_customlink_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='order ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='customer name')),
                ('form_responses', models.JSONField(default=dict, help_text='JSON object with field_label: response mappings', verbose_name='form responses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('custom_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customlink')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['custom_link', '-created_at'], name='orders_custom__9ebff2_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['order_id'], name='orders_order_i_88e57b_idx')],
            },
        ),
    ]
