# Generated by Django 5.1.4 on 2025-09-13 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe account ID')),
                ('charges_enabled', models.BooleanField(default=False, help_text='Whether the account can create charges', verbose_name='charges enabled')),
                ('payouts_enabled', models.BooleanField(default=False, help_text='Whether Stripe can send payouts to the account', verbose_name='payouts enabled')),
                ('details_submitted', models.BooleanField(default=False, help_text='Whether account details have been submitted', verbose_name='details submitted')),
                ('country', models.CharField(blank=True, help_text='Two-letter country code', max_length=2, verbose_name='country')),
                ('default_currency', models.CharField(default='usd', max_length=3, verbose_name='default currency')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='account email')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of each transaction kept as platform fee', max_digits=5, verbose_name='platform fee percentage')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='onboarding completed at')),
                ('requirements_due', models.JSONField(blank=True, help_text='Currently due requirements for the account', null=True, verbose_name='requirements due')),
                ('requirements_errors', models.JSONField(blank=True, help_text='Requirements that need to be fixed', null=True, verbose_name='requirements errors')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connect_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Connect account',
                'verbose_name_plural': 'Stripe Connect accounts',
                'db_table': 'stripe_connect_accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='checkout session ID')),
                ('payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='payment intent ID')),
                ('charge_id', models.CharField(blank=True, max_length=255, verbose_name='charge ID')),
                ('transfer_id', models.CharField(blank=True, help_text='ID of transfer to connected account', max_length=255, verbose_name='transfer ID')),
                ('total_amount', models.IntegerField(help_text='Total amount paid by customer (in cents)', verbose_name='total amount')),
                ('platform_fee', models.IntegerField(help_text='Platform commission (in cents)', verbose_name='platform fee')),
                ('seller_amount', models.IntegerField(help_text='Amount transferred to seller (in cents)', verbose_name='seller amount')),
                ('stripe_processing_fee', models.IntegerField(default=0, help_text="Stripe's processing fee (in cents)", verbose_name='Stripe processing fee')),
                ('currency', models.CharField(default='usd', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('transfer_status', models.CharField(blank=True, help_text='Status of transfer to seller', max_length=50, verbose_name='transfer status')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('refunded_amount', models.IntegerField(default=0, help_text='Amount refunded to customer (in cents)', verbose_name='refunded amount')),
                ('platform_fee_refunded', models.IntegerField(default=0, help_text='Platform fee refunded (in cents)', verbose_name='platform fee refunded')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='transferred at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='api.order')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.stripeconnectaccount')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe event ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('account_id', models.CharField(blank=True, help_text='Connected account ID if applicable', max_length=255, verbose_name='account ID')),
                ('data', models.JSONField(verbose_name='event data')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='api.paymenttransaction')),
                ('connect_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='api.stripeconnectaccount')),
            ],
            options={
                'verbose_name': 'Connect webhook event',
                'verbose_name_plural': 'Connect webhook events',
                'db_table': 'connect_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stripeconnectaccount',
            index=models.Index(fields=['user'], name='stripe_conn_user_id_ee34e6_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeconnectaccount',
            index=models.Index(fields=['stripe_account_id'], name='stripe_conn_stripe__6fa3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeconnectaccount',
            index=models.Index(fields=['charges_enabled', 'payouts_enabled'], name='stripe_conn_charges_6acf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order'], name='payment_tra_order_i_54c79b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['seller_account', '-created_at'], name='payment_tra_seller__df7baf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_intent_id'], name='payment_tra_payment_2cdde3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['-created_at'], name='payment_tra_created_94cd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='connectwebhookevent',
            index=models.Index(fields=['stripe_event_id'], name='connect_web_stripe__fd105f_idx'),
        ),
        migrations.AddIndex(
            model_name='connectwebhookevent',
            index=models.Index(fields=['event_type'], name='connect_web_event_t_b38223_idx'),
        ),
        migrations.AddIndex(
            model_name='connectwebhookevent',
            index=models.Index(fields=['processed', '-created_at'], name='connect_web_process_e5476d_idx'),
        ),
    ]
