# Generated by Django 5.1.4 on 2025-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_stripe_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='payment intent ID'),
        ),
    ]
