# Generated by Django 5.1.4 on 2025-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_fix_payment_intent_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='url',
            field=models.TextField(verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='stripeconnectaccount',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Percentage of each transaction kept as platform fee', max_digits=5, verbose_name='platform fee percentage'),
        ),
    ]
