# Generated by Django 5.1.4 on 2025-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_socialicon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affiliate_link',
            field=models.TextField(blank=True, help_text='Affiliate/purchase link for funnel injection', verbose_name='affiliate link'),
        ),
    ]
