# Generated by Django 5.1.4 on 2025-10-01 10:42

import cloudinary.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_userprofile_affiliate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLinkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this template', max_length=255, verbose_name='template name')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('type', models.CharField(default='generic', help_text="Product type (e.g., 'generic', 'digital_product', 'service', 'event', 'subscription')", max_length=50, verbose_name='type')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='template_thumbnail')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='subtitle')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='button text')),
                ('style', models.CharField(choices=[('callout', 'Callout'), ('button', 'Button'), ('checkout', 'Checkout'), ('collect_info', 'Collect Info')], default='callout', max_length=20, verbose_name='style')),
                ('checkout_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='template_checkout_image')),
                ('checkout_title', models.CharField(blank=True, max_length=100, verbose_name='checkout title')),
                ('checkout_description', tinymce.models.HTMLField(blank=True, verbose_name='checkout description')),
                ('checkout_bottom_title', models.CharField(blank=True, max_length=100, verbose_name='checkout bottom title')),
                ('checkout_cta_button_text', models.CharField(blank=True, max_length=50, verbose_name='checkout CTA button text')),
                ('checkout_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='checkout price')),
                ('checkout_discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='checkout discounted price')),
                ('additional_info', models.JSONField(blank=True, help_text='Product-specific information based on product type', null=True, verbose_name='additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'custom link template',
                'verbose_name_plural': 'custom link templates',
                'db_table': 'custom_link_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customlink',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Master template this link is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_links', to='api.customlinktemplate'),
        ),
    ]
