# Generated by Django 5.1.4 on 2025-10-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_customlinktemplate_customlink_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Master template this link is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_links', to='api.customlinktemplate'),
        ),
    ]
