# Generated by Django 5.1.4 on 2025-10-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_customlink_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email displayed on storefront', max_length=254, verbose_name='contact email'),
        ),
    ]
