# Generated by Django 5.1.4 on 2025-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_add_contact_email_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiloPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(help_text='System prompt for Milo AI assistant', verbose_name='system prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Milo Prompt',
                'verbose_name_plural': 'Milo Prompts',
                'db_table': 'milo_prompts',
                'ordering': ['-modified_at'],
            },
        ),
    ]
