# Generated by Django 5.1.4 on 2025-10-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_freebie_followup_email_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptinFollowupEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Email sequence number (1-20)', unique=True, verbose_name='step number')),
                ('delay_days', models.IntegerField(help_text='Days after opt-in to send email', verbose_name='delay days')),
                ('send_time', models.TimeField(default='10:00', help_text='Time of day to send email (e.g., 10:00 AM)', verbose_name='send time')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='Email content with template variables: {{ first_name }}, {{ sender_name }}, {{ affiliate_link }}, {{ personal_email }}', verbose_name='email body')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Opt-in Follow-up Email',
                'verbose_name_plural': 'Opt-in Follow-up Emails',
                'db_table': 'optin_followup_emails',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledOptinEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(help_text='Exact datetime to send email', verbose_name='scheduled for')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.optinfollowupemail')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optin_followup_emails', to='api.order')),
            ],
            options={
                'verbose_name': 'Scheduled Opt-in Email',
                'verbose_name_plural': 'Scheduled Opt-in Emails',
                'db_table': 'scheduled_optin_emails',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['sent', 'scheduled_for'], name='scheduled_o_sent_a6eca9_idx'), models.Index(fields=['order'], name='scheduled_o_order_i_23a50d_idx')],
            },
        ),
    ]
