# Generated by Django 5.1.4 on 2025-10-16 09:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_optinfollowupemail_scheduledoptinemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('access_token', models.TextField(help_text='Encrypted OAuth access token', verbose_name='access token')),
                ('refresh_token', models.TextField(help_text='Encrypted OAuth refresh token', verbose_name='refresh token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='token expiry')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='last synced')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'db_table': 'email_accounts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_emails', models.JSONField(default=list, verbose_name='to emails')),
                ('cc_emails', models.JSONField(blank=True, default=list, verbose_name='cc emails')),
                ('bcc_emails', models.JSONField(blank=True, default=list, verbose_name='bcc emails')),
                ('subject', models.TextField(blank=True, verbose_name='subject')),
                ('body_html', models.TextField(blank=True, verbose_name='body html')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file URLs', verbose_name='attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='api.emailaccount')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'db_table': 'email_drafts',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Gmail message ID', max_length=255, verbose_name='message ID')),
                ('thread_id', models.CharField(blank=True, max_length=255, verbose_name='thread ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='from email')),
                ('from_name', models.CharField(blank=True, max_length=255, verbose_name='from name')),
                ('to_emails', models.JSONField(default=list, verbose_name='to emails')),
                ('cc_emails', models.JSONField(blank=True, default=list, verbose_name='cc emails')),
                ('subject', models.TextField(blank=True, verbose_name='subject')),
                ('body_text', models.TextField(blank=True, verbose_name='body text')),
                ('body_html', models.TextField(blank=True, verbose_name='body html')),
                ('snippet', models.TextField(blank=True, help_text='Email preview text', verbose_name='snippet')),
                ('received_at', models.DateTimeField(verbose_name='received at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_starred', models.BooleanField(default=False, verbose_name='is starred')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='has attachments')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='labels')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.emailaccount')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'db_table': 'email_messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(help_text='Gmail attachment ID', max_length=255, verbose_name='attachment ID')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('size', models.BigIntegerField(help_text='File size in bytes', verbose_name='size')),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='Stored attachment file', max_length=255, null=True, verbose_name='email_attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.emailmessage')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'db_table': 'email_attachments',
                'ordering': ['filename'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['account', '-received_at'], name='email_messa_account_741c46_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_id'], name='email_messa_message_38c96a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['thread_id'], name='email_messa_thread__b5dfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['is_read'], name='email_messa_is_read_4db32a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('account', 'message_id')},
        ),
    ]
