# Generated by Django 5.1.4 on 2025-10-29 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_email_integration_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Canva OAuth access token', verbose_name='access token')),
                ('refresh_token', models.TextField(help_text='Canva OAuth refresh token', verbose_name='refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='token type')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('scope', models.TextField(blank=True, help_text='OAuth scopes granted', verbose_name='granted scope')),
                ('canva_user_id', models.CharField(blank=True, max_length=255, verbose_name='Canva user ID')),
                ('canva_team_id', models.CharField(blank=True, max_length=255, verbose_name='Canva team ID')),
                ('canva_display_name', models.CharField(blank=True, max_length=255, verbose_name='Canva display name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canva_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canva Connection',
                'verbose_name_plural': 'Canva Connections',
                'db_table': 'canva_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanvaDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_id', models.CharField(help_text='Canva design ID', max_length=255, unique=True, verbose_name='design ID')),
                ('design_type', models.CharField(default='doc', help_text='Type of design (e.g., doc, Presentation)', max_length=100, verbose_name='design type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('edit_url', models.URLField(blank=True, help_text='URL to edit design in Canva', max_length=1000, verbose_name='edit URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Design thumbnail', max_length=1000, verbose_name='thumbnail URL')),
                ('export_url', models.URLField(blank=True, help_text='URL to download exported design', max_length=1000, verbose_name='export URL')),
                ('export_format', models.CharField(default='png', help_text='Export format (png, jpg, pdf)', max_length=50, verbose_name='export format')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='exported at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('editing', 'Editing'), ('completed', 'Completed'), ('exported', 'Exported'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional design metadata', verbose_name='metadata')),
                ('opened_count', models.PositiveIntegerField(default=0, help_text='Number of times design was opened', verbose_name='opened count')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='last opened at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='api.canvaconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canva_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canva Design',
                'verbose_name_plural': 'Canva Designs',
                'db_table': 'canva_designs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='canva_desig_user_id_1c0985_idx'), models.Index(fields=['design_id'], name='canva_desig_design__13e7e0_idx')],
            },
        ),
    ]
