# Generated by Django 5.1.4 on 2025-10-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_email_integration_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectwebhookevent',
            name='account_id',
            field=models.CharField(blank=True, help_text='Connected account ID if applicable', max_length=255, null=True, verbose_name='account ID'),
        ),
    ]
