# Generated by Django 5.1.4 on 2025-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_make_account_id_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu item title', max_length=255, verbose_name='title')),
                ('link', models.URLField(help_text='URL to display in iframe', verbose_name='link')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'iframe menu item',
                'verbose_name_plural': 'iframe menu items',
                'db_table': 'iframe_menu_items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
