# Generated by Django 5.1.4 on 2025-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_canvaconnection_canvadesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvadesign',
            name='export_url',
            field=models.URLField(blank=True, help_text='URL to download exported design', max_length=1000, null=True, verbose_name='export URL'),
        ),
    ]
