# Generated by Django

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing IframeMenuItem records."""
    IframeMenuItem = apps.get_model('api', 'IframeMenuItem')
    for item in IframeMenuItem.objects.all():
        if not item.slug:
            item.slug = slugify(item.title)
            # Handle potential duplicates
            base_slug = item.slug
            counter = 1
            while IframeMenuItem.objects.filter(slug=item.slug).exclude(id=item.id).exists():
                item.slug = f"{base_slug}-{counter}"
                counter += 1
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_iframemenuitem'),
    ]

    operations = [
        # Add slug field without unique constraint first
        migrations.AddField(
            model_name='iframemenuitem',
            name='slug',
            field=models.SlugField(default='', max_length=255, help_text='URL-friendly identifier'),
            preserve_default=False,
        ),
        # Add icon field
        migrations.AddField(
            model_name='iframemenuitem',
            name='icon',
            field=models.CharField(default='ExternalLink', help_text='Lucide React icon name', max_length=100, verbose_name='icon'),
        ),
        # Populate slugs for existing records
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        # Now add unique constraint
        migrations.AlterField(
            model_name='iframemenuitem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, help_text='URL-friendly identifier', verbose_name='slug'),
        ),
    ]
