# Generated by Django 5.1.4 on 2025-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_canvadesign_export_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creators_code',
            field=models.TextField(blank=True, help_text="Creator's referral or promotional code", verbose_name='creators code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nurture_email',
            field=models.TextField(blank=True, help_text='Nurture email content or template', verbose_name='nurture email'),
        ),
    ]
