# Generated by Django 5.1.4 on 2025-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_userprofile_creators_code_userprofile_nurture_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optinfollowupemail',
            options={'ordering': ['program', 'step_number'], 'verbose_name': 'Opt-in Follow-up Email', 'verbose_name_plural': 'Opt-in Follow-up Emails'},
        ),
        migrations.AddField(
            model_name='optinfollowupemail',
            name='program',
            field=models.CharField(choices=[('TWC', 'The Wealth Creator'), ('TCC', 'The Creators Code')], default='TCC', help_text='Which program this email sequence is for', max_length=3, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='optinfollowupemail',
            name='step_number',
            field=models.IntegerField(help_text='Email sequence number (1-20)', verbose_name='step number'),
        ),
        migrations.AlterUniqueTogether(
            name='optinfollowupemail',
            unique_together={('program', 'step_number')},
        ),
    ]
