# Generated by Django 5.1.4 on 2025-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_slug_icon_to_iframe_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='accessible_iframe_menu_items',
            field=models.ManyToManyField(blank=True, help_text='Iframe menu items this user can access', related_name='users_with_access', to='api.iframemenuitem'),
        ),
    ]
