# Generated by Django 5.1.4 on 2025-11-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_optinfollowupemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_automation_enabled',
            field=models.BooleanField(default=True, help_text='Whether this lead should receive automated follow-up emails. Set to False if affiliate wants to send manual emails.', verbose_name='email automation enabled'),
        ),
    ]
