# Generated by Django 5.1.4 on 2025-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_automation_enabled',
            field=models.BooleanField(default=True, help_text='Whether this lead should receive automated follow-up emails. Set to False if affiliate wants to send manual emails.', verbose_name='email automation enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_automation_enabled',
            field=models.BooleanField(default=True, help_text='Default setting for email automation on new leads. When enabled, all new leads will automatically receive follow-up emails unless individually disabled.', verbose_name='email automation enabled by default'),
        ),
    ]
