# Generated by Django 5.1.4 on 2025-11-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_order_email_automation_enabled'),
    ]

    operations = [
        # Set database-level default to TRUE
        migrations.RunSQL(
            sql='ALTER TABLE orders ALTER COLUMN email_automation_enabled SET DEFAULT TRUE;',
            reverse_sql='ALTER TABLE orders ALTER COLUMN email_automation_enabled DROP DEFAULT;'
        ),
        # Update any existing NULL or FALSE values to TRUE
        migrations.RunSQL(
            sql='UPDATE orders SET email_automation_enabled = TRUE WHERE email_automation_enabled IS NULL OR email_automation_enabled = FALSE;',
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
