# Generated by Django 5.1.4 on 2025-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_fix_email_automation_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_automation_enabled',
            field=models.BooleanField(default=True, help_text='Default setting for email automation on new leads. When enabled, all new leads will automatically receive follow-up emails unless individually disabled.', verbose_name='email automation enabled by default'),
        ),
    ]
