# Generated by Django 5.1.4 on 2025-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_userprofile_email_automation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_canva',
            field=models.BooleanField(default=True, help_text='Canva Designs page access', verbose_name='Can Access Canva'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_community',
            field=models.BooleanField(default=True, help_text='Community page access', verbose_name='Can Access Community'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_faq',
            field=models.BooleanField(default=True, help_text='FAQ page access', verbose_name='Can Access FAQ'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_inbox',
            field=models.BooleanField(default=True, help_text='Email inbox page access', verbose_name='Can Access Inbox'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_prompt_library',
            field=models.BooleanField(default=True, help_text='Prompt Library page access', verbose_name='Can Access Prompt Library'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_training',
            field=models.BooleanField(default=True, help_text='Elevate Training page access', verbose_name='Can Access Training'),
        ),
    ]
