# Generated by Django 5.1.4 on 2025-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_page_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='can_access_milo',
            field=models.BooleanField(default=True, help_text='Milo AI chatbot access', verbose_name='Can Access Milo'),
        ),
    ]
