# Generated by Django 5.1.4 on 2025-11-17 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_milo_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='milo_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Available credits for Milo AI calls. 0.5 credits = 1 minute', max_digits=10, verbose_name='Milo credits'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_credits_purchased',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lifetime total credits purchased', max_digits=10, verbose_name='total credits purchased'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_credits_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lifetime total credits used', max_digits=10, verbose_name='total credits used'),
        ),
        migrations.CreateModel(
            name='MiloCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, help_text='Eleven Labs conversation ID if available', max_length=255, verbose_name='conversation ID')),
                ('call_duration_seconds', models.IntegerField(default=0, help_text='Total duration of the call in seconds', verbose_name='call duration (seconds)')),
                ('credits_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Credits deducted for this call (0.5 per minute)', max_digits=10, verbose_name='credits used')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milo_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milo Call Log',
                'verbose_name_plural': 'Milo Call Logs',
                'db_table': 'milo_call_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage - Milo Call'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('bonus', 'Bonus Credits')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credits added, negative for credits used', max_digits=10, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Credit balance after this transaction', max_digits=10, verbose_name='balance after')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('payment_transaction', models.ForeignKey(blank=True, help_text='Link to payment if this is a purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='api.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('milo_call_log', models.OneToOneField(blank=True, help_text='Link to Milo call if this is usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transaction', to='api.milocalllog')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='milocalllog',
            index=models.Index(fields=['user', '-created_at'], name='milo_call_l_user_id_bf2d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='milocalllog',
            index=models.Index(fields=['conversation_id'], name='milo_call_l_convers_a7d971_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='credit_tran_user_id_c82af7_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='credit_tran_transac_0eee54_idx'),
        ),
    ]
